language: python
python:
  - "2.7"
install: ./install_deps
notifications:
  slack:
    secure: sdA93oGSoH96PIj0nwcpIu3ocZAY9lC5YuCl18eK+ux8xQYANOuX7CXTQ0T0bk940zan1HPKQZhnX+zfrStEwMZV+PdXzWKSuHA/yPTCZDiBKx4HYk7KrdQs7JOFuF1U6g2ElMG4iU/QD5AQVysqApCLMjqKN/budoxPEHjrrHl9etX70bmS1pnZgZnWK2dzWsqh/NjpadL2U+Kujcj6MqN4g65P7FeV6tkBVyCvW/3KdJzM1ldRhe0Np4+xHpx+8RbZfFPdnS6E3HG/l/J8elFCj/AioQ/MatiOyeOep8686TUoGS3F+Bsr5D137RpRnzu58qPs2r2GTp7pIICxRqlvLwPVb1WYDyxd3GJDcqGv0Drb4WGVJ4Ig44CYs4OHHWeLXzWbhDCq5ypdexkVs4OqkjO9GM9T3uGzZjSjZ1rurC0vYWxpmy47MbgGzmGRxK6SLIR+9G6hpz6JlKurQT5HMDL4SUUsmA+lCCkoV7ds3UA/Om7AO0xL++VjtzqEnBd4lueKzSdnMaeFcZq2RaZuJPHa0knXwL+cyJqbhZKOA39X+hmc7TWvWdgTYqRWE6mRllMXCo8XBkYy3EwoYfUNiZ6CT4n8DUmIPLJUzRoPrU7Eze2wFoJ8YQbdTyJ+jMhZa0zR4BmI9e29ujtMLoT2U8I5LrQaDvUQp9aLv64=
script:
  - python manage.py test
